version: '3'
services:
  redis:
    container_name: redis_container
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
volumes:
  postgres:
